-- CreateTable
CREATE TABLE `caa1_shop_stock_item_db` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bar_code` VARCHAR(255) NULL,
    `bill_comment` TEXT NULL,
    `brand_code` VARCHAR(255) NULL,
    `brand_id` VARCHAR(255) NULL,
    `brand_name` VARCHAR(255) NULL,
    `cat_id` INTEGER NULL,
    `cat_name` VARCHAR(255) NULL,
    `color_id` INTEGER NULL,
    `color_name` VARCHAR(255) NULL,
    `cur_meter` DOUBLE NULL,
    `cur_qty` DOUBLE NULL,
    `design_id` INTEGER NULL,
    `design_name` VARCHAR(255) NULL,
    `edition` VARCHAR(255) NULL,
    `entry_meter` DOUBLE NULL,
    `entry_qty` DOUBLE NULL,
    `entry_return_meter` DOUBLE NULL,
    `entry_return_qty` DOUBLE NULL,
    `fabric_id` INTEGER NULL,
    `fabric_name` VARCHAR(255) NULL,
    `gstper` INTEGER NULL,
    `indate` DATE NULL,
    `insert_date` VARCHAR(255) NULL,
    `insert_user` VARCHAR(255) NULL,
    `issue_meter` DOUBLE NULL,
    `issue_qty` DOUBLE NULL,
    `issue_return_meter` DOUBLE NULL,
    `issue_return_qty` DOUBLE NULL,
    `item_code` VARCHAR(255) NULL,
    `item_id` INTEGER NULL,
    `item_name` VARCHAR(255) NULL,
    `item_remarks` TEXT NULL,
    `mrp_rate` VARCHAR(255) NULL,
    `praty_id` INTEGER NULL,
    `pur_rate` DOUBLE NULL,
    `sale_rate` DOUBLE NULL,
    `shop_id` INTEGER NULL,
    `status` VARCHAR(1) NOT NULL DEFAULT '1',
    `stoct_update_date` DATE NULL,
    `transfer_return_qty` DOUBLE NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
